# Generated by Django 4.2.3 on 2023-11-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_banner_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='article',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.contents'),
        ),
    ]
