# Generated by Django 4.2.3 on 2023-11-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_banner_article_remove_banner_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
