# Generated by Django 4.2.3 on 2023-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, null=True, unique=True)),
                ('image', models.ImageField(default='no_image.png', null=True, upload_to='music_images/')),
            ],
        ),
    ]
