# Generated by Django 4.2.3 on 2023-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_musicofday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='category',
        ),
        migrations.AddField(
            model_name='contents',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='contents', to='home.category'),
        ),
    ]
